export enum IMuscles {
	VOID = "",
	BICEP = "biceps",
	TRICEP = "triceps",
	ESPALDA = "espalda",
	DORSALES = "dorsales",
	CUADRICEPS = "cuadriceps",
	IZQUIOTIBIALES = "izquiotibiales",
	GEMELOS = "gemelos",
	HOMBRO = "hombro",
	ABDOMINALES = "abdominales",
	GLUTEO = "gluteo",
	PECHO = "pecho",
	OTRO = "otro",
}
